### ISSUE TITLE
Publish pydoctor API docs

### ISSUE THREAD

**Issue by adiroiban** [twisted/pydoctor#106]
It looks like pydoctor does not have its own API publicly documented.

For example, from Twisted I can not link to pydoctor API as I don't know where to point it

This might also need documentation to explain how to link to inter-pydoctor documentations :)

**Comment by tristanlatr** [comment]
Is this issue has anything to do with the custom system class usage ? I would love more information about how to handled versioning in pydoctor. 

Where can I find the code that generates the "Go to the latest version of this document." link in Twisted docs ?

I could tackle the prose docs at the same time of generating pydoctor's own API docs. 
That would make sens... 

@mthuurne

**Comment by adiroiban** [comment]
The Twisted template is here https://github.com/twisted/twisted/tree/trunk/src/twisted/python/_pydoctortemplates

Based on the work from here https://github.com/twisted/twisted/pull/1466 maybe pydoctor can have the API documentation inside read the docs.

**Comment by tristanlatr** [comment]
Hi @adiroiban ,

Thanks for the infos.

What I understand is :
- The usage of custom templates and versioning is not actually supported by `pydoctor` since you need to apply a patch to the `pydoctor.templatewriter.util.templatefile` function. See https://github.com/twisted/twisted/blob/trunk/src/twisted/python/_release.py#L271
- The custom system class used by Twisted to document the API does:
    - Make private the `tests` modules but not `twisted.test.proto_helpers`
    - Generate some deprecation notice in pydoctor based on `twisted.python.deprecate.deprecated` decorator
    - Handle not logical documentation object location in zope interface sphinx autodoc.

- It's basically a mess (No offense, all of this require a hight level of technique, what I mean is Twisted is strongly coupled with pydoctor internals and the reverse is also true)

 I'm not going to try to fully document how to customize `pydoctor` builds myself as I'm not familiar enough with all of this.

**Comment by mthuurne** [comment]
The current API of pydoctor is not great: it's something that has been grown over a long time and the requirements only became clear along the way. I don't think it's a good idea to freeze the current API, since we'd be stuck with something that is hard to use and easy to break. But that means that any kind of plugin will be tightly coupled, as Twisted currently is.

Once pydoctor has sufficiently high mypy coverage, we can start thinking about refactoring to simplify the API.

In the mean time, I think it's fine if the documentation discourages the use of `--system-class` and refers to Twisted as an example for people who want to use it anyway, with the disclaimer that the pydoctor API is not stable.

**Comment by adiroiban** [comment]
Well.. I think that the API can still be published with a big warning that the API is not stable.

The reason to have the API docs published is practice some "eat your own dog food" and it can also server as an example for how pydoctor API docs work and look... outside of Twisted.

But I am ok if this is not done yet.

**Comment by tristanlatr** [comment]
I think this one can be closed
