### ISSUE TITLE
Parameter type information visually hard to find

### ISSUE THREAD

**Issue by DanielSank** [twisted/pydoctor#121]
Consider the documentation found at (screenshot below) https://twistedmatrix.com/documents/current/api/twisted._threads.IWorker.html

At present, the type information is set off
- By the string "type"
- At the end of the parameter description
- In parentheses

Parameter types are essential information. Consider
- Putting the type a the beginning of the parameter description
- Omitted the unnecessary word "type"
- Giving the parameters their own colored box

![pydoc_note](https://cloud.githubusercontent.com/assets/4584456/17146292/9239a640-52f9-11e6-8519-34ef7fc5609b.png)

**Comment by mthuurne** [comment]
I agree that having the type in parentheses at the end is not great. I'm considering to either put the type immediately after the name, similar to PEP 484 annotations (`task: Callable`), or put it in a separate column.

Types can get quite long, for example the full PEP 484 syntax would be `task: Callable[[], None]` (a 0-argument callable that returns nothing). Type information becomes even longer when non-builtin types are used as type arguments, for example a list of workers would be `List[twisted._threads.IWorker]`. Therefore it might be better to have the documentation body on a separate line, below the name + type. It would then look like a definition list rather than a table.

**Comment by tristanlatr** [comment]
I think the parameters types should be right after the param name, in the same "column", like https://geopy.readthedocs.io/en/stable/#nominatim

**Comment by tristanlatr** [comment]
> Therefore it might be better to have the documentation body on a separate line, below the name + type. It would then look like a definition list rather than a table.

This is not exactly what I did, I stuck with the common way to show arguments types: In parenthesis on the same column as the arg name. 
I fix the size of the argument name column to 25%. 
To handle the longer type names, I've add potential line breaks after `[` or `, ` in type rendering: 
<img width="701" alt="by default 2021-01-14 at 10 33 28 AM" src="https://user-images.githubusercontent.com/19967168/104612208-f35a7c80-5653-11eb-8a76-4cb37b3e5c96.png">

**Comment by tristanlatr** [comment]
after second try, it looks like this (on a small screen): 

![Capture d’écran, le 2021-01-30 à 11 14 43](https://user-images.githubusercontent.com/19967168/106361545-88b06e80-62ec-11eb-9b74-72b585ebc291.png)

**Comment by mthuurne** [comment]
I think that latest version is a big improvement over the current implementation.

The font baseline isn't aligned at the moment: the type names are a few pixels lower than the parameter names. There is probably something that could be done in CSS to fix that.

If the type cell is using in a flex layout (I think I read that in a commit title), maybe enable wrapping? That way, instead of
```
fields: Sequence[
        Field]
```
we would have
```
fields:
Sequence[Field]
```

**Comment by tristanlatr** [comment]
Yep I did do that after: only for screens smaller than 650px , 
Please see the changes here: https://pydoctor--299.org.readthedocs.build/en/299/api/pydoctor.epydoc2stan.html 

I'll merge the master and mark the PR as ready in a few
