### ISSUE TITLE
Only first value of multi-value parameter tilde-expanded

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#2]
Originally reported as Twisted issue 2623:

> This is due to the fact that the config file parsing code invokes os.expanduser before splitting on commas.

---

Imported from Launchpad using lp2gh.
- date created: 2009-08-06T18:50:01Z
- owner: exarkun
- the launchpad url was https://bugs.launchpad.net/bugs/410004

**Comment by tristanlatr** [comment]
I think we should completely deprecate the actual config file parsing since it's really horrible.
At the same time, the `optparse` options can be refactored to use something that belongs more to the twenty-first century.

We could use https://pypi.org/project/ConfigArgParse/ to handle the fact that all options can be read from file and overridden from CLI.

**Comment by tristanlatr** [comment]
I have to send a few patches to ConfigArgParse for this module to be the real deal for us. First there is https://github.com/bw2/ConfigArgParse/pull/229, there would be a few other stuff also...
