### ISSUE TITLE
Better support for restructuredtext directives

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#225]
Hello,

Some of the restructuredtext directives are supported, like `.. contents::` which is great !

But the classic `.. warning::` or `.. note::` are not supported and are triggering the following warning:
```
bad docstring: NotImplementedError: <class 'pydoctor.epydoc.markup.restructuredtext._EpydocHTMLTranslator'> visiting unknown node type: warning
```

What reST directives pydoctor is currently supporting ? 

Would be cool to support `.. warning::`, `.. note::` and others :)

reST docs about directives here: https://docutils.sourceforge.io/0.4/docs/ref/rst/directives.html#admonitions

**Comment by mthuurne** [comment]
We inherited reST support from epydoc and I think epydoc only supports the directives that can be mapped to equivalents in epytext. The supported fields can be found [here in the code](https://github.com/twisted/pydoctor/blob/master/pydoctor/epydoc/markup/restructuredtext.py#L70).

I agree that more support would be good to add, but I'll have to say "patches are welcome" here, since I have too many other things to work on already.

**Comment by tristanlatr** [comment]
Thanks, that ok.

But I don't get something, `.. contents::` works but it does not appear in the code.
So some of the directive are handled in `docutils.parsers.rst` but not all of them ?

**Comment by mthuurne** [comment]
I dug into the docutils source for a bit and it seems the `contents` directive generates a `topic` node. Since [`HTMLTranslator`](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/writers/_html_base.py) implements `visit_topic()`, it won't trigger a "visiting unknown node type" error.

So indeed, whether a directive works out of the box depends on whether docutils provides a default `visit_<node_type>()` implementation for it in `HTMLTranslator`.

**Comment by tristanlatr** [comment]
Pydoctor now suports reST admonitions!
