### ISSUE TITLE
Handle private deprecated code

### ISSUE THREAD

**Issue by adiroiban** [twisted/pydoctor#234]
This test is failing in twisted  https://github.com/twisted/twisted/blob/da0bbc698cbb2a48b198987663db0a0c9a19ab8d/src/twisted/python/test/test_release.py#L555

It was green as it was skipped for a long time.

It looks like the problem is with the hide/show private API feature.

```python

from twisted.python.deprecate import deprecated
from incremental import Version
from twisted.python import deprecate
import incremental

@deprecated(Version('Twisted', 15, 0, 0), 'Baz')
def foo():
    'text in foo docstring'

@deprecate.deprecated(incremental.Version('Twisted', 16, 0, 0))
def _bar():
    'should also appear in _bar output'

@deprecated(Version('Twisted', 14, 2, 3), replacement='stuff')
class Baz:
    pass
```

To reproduce this, I am just running `pydoctor test_file.py` and then open the apidocs dir in a browser.

**Comment by mthuurne** [comment]
The skip logic is wrong on so many levels:
- `skip = ""` forces skipping
- `pydoctor.version_info` was removed when pydoctor adopted Incremental, back in 2017
- instead of skipping on network errors, the tests should not rely on external intersphinx inventories

The error messages state `a bytes-like object is required, not 'str'`, so I'm assuming there is some code that wasn't properly converted to Python 3 and no-one noticed because the tests had been skipped for years.

**Comment by mthuurne** [comment]
I can reproduce the problem, by the way, if I use this command line:
```
pydoctor --system-class twisted.python._pydoctor.TwistedSystem test_file.py
```

**Comment by mthuurne** [comment]
I think the problem is in Twisted, to be precise in `getDeprecated()` in `src/twisted/python/_pydoctor.py`:
```diff
- fn = self.expandName("".join(astbuilder.node2dottedname(a.func)))
+ fn = self.expandName(".".join(astbuilder.node2dottedname(a.func)))
```
With that fix, `deprecate.deprecated` is properly expanded to `twisted.python.deprecate.deprecated` and the deprecation notice is added to the output.

There are still some oddities though:
- no deprecation notice is shown for the class
- the decoration (`@` line) is shown above the `def` line for `_bar` but not for `foo`

**Comment by mthuurne** [comment]
The reason the class deprecation is missing is that the `visitClass()` method isn't called anymore since pydoctor switched to the `ast` module for processing Python code.

**Comment by adiroiban** [comment]
Thanks. I will try to move this to twisted/twisted  and fix it there.

This was not detected earlier as the pydoctor tests on twisted were always skipped.

I am re-enabling the test execution and after that this issue can be fixed in a separate PR.

**Comment by adiroiban** [comment]
I think that this can be closed as it will be fixed in https://github.com/twisted/twisted/pull/1473/
