### ISSUE TITLE
Report content problems with non-zero exit code

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#248]
Once we have a robust logging system (see #112), it would be nice if pydoctor could return a non-zero exit code if it encountered content problems when generating docs.

For the system test, it is important though that we have an option to disable this feature, since during system tests we don't want content problems to fail the build, but we do want to know if pydoctor crashed or couldn't do its job for non-content reasons.

**Comment by adiroiban** [comment]
One option that I am using for my tools.

Instead of a logger, I use a "reporter" object.

The report is very similar to the logger in that it received messages of type "info", "warning" and "error" and each message has a text, source file path and source line number.... in this way I can plug it into text editor UI reporting :)

The reporter can be used to print to stdout or stderr and at the end of the run the report can give a report with number of errors / warning / info messages.

So it's like a logger... but keeps track of error numbers...and that can be used to exit with -1 ... or exit at first error ... etc.

core pydoctor functionality will focus on just reporting the errors as fast and as precise as possible and the reporter will decide what to do with the error and when and how to exit.

**Comment by mthuurne** [comment]
I did [something similar](https://github.com/mthuurne/retroasm/blob/master/src/retroasm/linereader.py#L237) in one of my other projects. I even merged the line reading with the reporter there, so the file + line number is automatically available. But that kind of coupling would not work well for file formats that have constructs that span multiple lines, like docstrings.

In any case, it's possible to keep track of source locations using the `extra` feature of the standard library logging framework. And I think Twisted's logging is designed to make logging of non-string information easier.
