### ISSUE TITLE
--add-package should fail when directory does not exists.

### ISSUE THREAD

**Issue by adiroiban** [twisted/pydoctor#255]
I have this tox env

```
[testenv:apidocs]
description = Build only the API documentation

commands =
    pydoctor \
    --add-package=bla_pydoctor \
    --project-name=pydoctor \
    --project-url=https://github.com/twisted/pydoctor/ \
    --html-viewsource-base=https://github.com/twisted/pydoctor/tree/master \
    --html-output=build/apidocs \
    --project-base-dir="{toxinidir}" \
    --docformat=epytext \
    --intersphinx=https://docs.python.org/3/objects.inv \
    --make-html
```

And it reporting that all is ok **adding module /home/adi/chevah/pydoctor/bla_pydoctor**

```
$ tox -e apidocs

adding module /home/adi/chevah/pydoctor/bla_pydoctor
writing html to build/apidocs using pydoctor.templatewriter.writer.TemplateWriter
starting ModuleIndexPage ...took 0.000845s
starting ClassIndexPage ...took 0.000718s
starting IndexPage ...took 0.001189s
starting NameIndexPage ...took 0.000789s
starting UndocumentedSummaryPage ...took 0.000718s
Generating objects inventory at build/apidocs/objects.inv
___________________________________ summary ____________________________________
  apidocs: commands succeeded
  congratulations :)
```

**Comment by mthuurne** [comment]
Note that `--add-package` adds a package directory, not a package name (we had a bit of confusion about this on IRC).

From a quick look at the code of `pydoctor.driver.main()`, it seems to work like this:
- combine paths from `--add-package`, `--add-module` and arguments into a single list
- treat all existing directories as packages, the rest as modules
- modules are silently ignored when they don't have a known file extension such as `.py`

The fact that paths are accepted as arguments is not documented in `pydoctor --help`.

I don't think combining everything into a singe list is a good idea, since it makes it much more difficult to do proper error checking and reporting. It is fine to use auto-detection on paths passed as arguments, but paths that are explicitly added as a module or package should only be processed as such.

Instead of `System.addModuleFromPath()` ignoring paths that don't match known extensions, it would be better to only call it for known extensions when traversing a source tree recursively. That way, paths with unknown extensions that are passed from the command line can be reported as errors.

**Comment by mthuurne** [comment]
Also filtering out duplicate paths should be done inside the `System` class and not in the `driver` module:
- so potential other uses of the `System` class also get this behavior
- because the current filter only filters out duplicate paths in the command line arguments, but if there is overlap with recursively discovered paths, duplicates won't be discovered

**Comment by adiroiban** [comment]
> I don't think combining everything into a singe list is a good idea,

+1

----

I am +1 for deprecating --add-package and --add-module and just using positional arguments.

**Comment by mthuurne** [comment]
Arguments are a simpler interface, so I agree we should document and encourage their use.

If we get rid of the combined list, `--add-package` and `--add-module` do bypass the auto-detection, which in theory could have some value. However, as the auto-detection is just "if it's a file, assume it's a module; if it's a directory, assume it's a package", I don't see any scenario in which it is useful to avoid it. Without a use case, deprecating the options is probably a good idea.

**Comment by adiroiban** [comment]
Ok... so thare are 2 tasks here:

1. Deprecated -add-package and --add-module
2. Update the pydoctor to fail when a provided file or dir doesn't exists.
