### ISSUE TITLE
Issues in --introspect-c-modules

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#287]
Hello,

I'm trying to generate https://github.com/igraph/python-igraph API docs, which works great for the python part (expect a few Epytext tags). 

Here is a test command that tries to document C modules only. 

```
pydoctor \
            --project-name=python-igraph \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir="$(pwd)" \
            --docformat=epytext \
            --introspect-c-modules \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./src/_igraph/attributes.*
adding module .../src/_igraph/attributes.c
adding module .../src/_igraph/attributes.h
writing html to ./apidocs using pydoctor.templatewriter.writer.TemplateWriter
starting ModuleIndexPage ...took 0.004017s
starting ClassIndexPage ...took 0.002942s
starting IndexPage ...took 0.005538s
starting NameIndexPage ...took 0.002279s
starting UndocumentedSummaryPage ...took 0.001610s
Generating objects inventory at ./apidocs/objects.inv
```

It does not generates anything.

Empty name index. 

Any clue?

**Comment by mthuurne** [comment]
It introspects them, which means it loads the compiled extension into the Python VM and then inspects the module contents. It looks you are trying to process the C source instead, which is not supported.

**Comment by ntamas** [comment]
Hello -- I'm the author of the `python-igraph` library and we are looking into replacing our old Epydoc-based API documentation with PyDoctor as that would allow us to keep the old Epytext markup for the docstrings. (Epydoc itself broke when we dropped support for Python 2.7 and started to introduce Python 3 syntax throughout the codebase).

To put things into context: `python-igraph` is the Python interface to `igraph`, a low-level C library for graphs. The main Python module, `igraph`, contains a C extension (the `igraph._igraph` module) with lots of classes and functions that are documented with Epytext markup in the C code itself. Classes in the `igraph` module occasionally import and extend classes from `igraph._igraph` to provide a more "pythonic" interface that would be hard to implement in the Python-to-C glue layer.

PyDoctor currently fails to parse the markup in `igraph._igraph`, and I managed to track the issue down to the ordering of files in the `addPackage()` method in `model.py`. In this function, the files in a Python package are processed in the order returned by `sorted(os.listdir(dirpath))`. In igraph's case, on my computer, the main `igraph` folder contains _two_ files for the `_igraph` submodule:

* `_igraph.py`, which is a stub loader added by `setuptools`, and
* `_igraph.cpython-39-darwin.so`, which is the compiled C extension on macOS with Python 3.9.

Due to the alphabetic ordering performed by `sorted(...)`, `_igraph.cpython-39-darwin.so` comes first. It gets parsed and traversed by the `introspectModule()` function, and the module contents are saved correctly in `self.allobjects`. However, `_igraph.py` is then processed next, and a completely new module instance is created, which overwrites the one stored previously in `self.allobjects`. For me it looks like `introspectModule()` is prepared for the case when the module already has an object in `self.allobjects` (it uses `ensureModule()` and does not create a module on its own), but `addModule()` is not. The generated API documentation then contains the stub loader (`_igraph.py`) and its generated `__bootstrap__` function but not the contents of the "real" `igraph._igraph` module.

When I manually change the sort order in `sorted(os.listdir(dirpath))` to make sure that `_igraph.py` comes first and work around a few additional issues in `templatewriter/pages/table.py` and similar files (mostly related to trying to retrieve the `is_async` attribute on something that does not have such an attribute), I can generate the documentation for `igraph._igraph` successfully.

So, all in all, I think there's a bug in the handling of modules in `addPackage()` where it is assumed that the pure Python stub loaders (added by `setuptools`) are always parsed earlier than the corresponding C extension files. I'd appreciate if one of the core devs of PyDoctor could confirm that this is indeed the case. I would be happy to start working on a patch but I'd like to know whether I'm barking up the wrong tree or not.

**Comment by ntamas** [comment]
For posterity's sake, here is the patch that I currently use on top of 21.2.0 to process the inner C module from `python-igraph`, along with a bit of extra code that moves `_igraph.py` in front of `_igraph.cpython-39-darwin.so` in the file listing:

```diff
diff --git a/pydoctor/astbuilder.py b/pydoctor/astbuilder.py
index febfb17..161bb5b 100644
--- a/pydoctor/astbuilder.py
+++ b/pydoctor/astbuilder.py
@@ -189,7 +189,7 @@ class ModuleVistor(ast.NodeVisitor):
             self.newAttr = None

     def visit_Module(self, node: ast.Module) -> None:
-        assert self.module.docstring is None
+        # assert self.module.docstring is None

         self.builder.push(self.module, 0)
         if len(node.body) > 0 and isinstance(node.body[0], ast.Expr) and isinstance(node.body[0].value, ast.Str):
diff --git a/pydoctor/model.py b/pydoctor/model.py
index 09402c9..47d112c 100644
--- a/pydoctor/model.py
+++ b/pydoctor/model.py
@@ -808,15 +808,17 @@ class System:

     def _introspectThing(self, thing: object, parent: Documentable, parentMod: _ModuleT) -> None:
         for k, v in thing.__dict__.items():
-            if (isinstance(v, (types.BuiltinFunctionType, types.FunctionType))
+            if (isinstance(v, (types.BuiltinFunctionType, types.FunctionType, types.MethodDescriptorType))
                     # In PyPy 7.3.1, functions from extensions are not
                     # instances of the above abstract types.
-                    or v.__class__.__name__ == 'builtin_function_or_method'):
+                    or (hasattr(v, "__class__") and v.__class__.__name__ == 'builtin_function_or_method')):
                 f = self.Function(self, k, parent)
                 f.parentMod = parentMod
                 f.docstring = v.__doc__
                 f.decorators = None
                 f.signature = Signature()
+                f.is_async = False
+                f.annotations = {}
                 self.addObject(f)
             elif isinstance(v, type):
                 c = self.Class(self, k, parent)
```

I am still missing a few things from the generated documentation (like class methods on classes defined in the C extension) and I will keep on working on this in the next few days. If C extensions are within the scope of PyDoctor and you are interested in a PR, let me know.

**Comment by mthuurne** [comment]
C extensions are part of the Python ecosystem, so having support for that is useful. That support hasn't seen a lot of use, so it's broken in places, as you saw. I'm willing to review and merge PRs for things that are broken or missing, as well as help with implementation should you get stuck somewhere.

It would be good to have unit tests that reproduce the things that didn't work, so we don't accidentally break them again in the future.

For handling modules that exists twice (as a stub and as a native module), we could solve that by building a dictionary of modules, before analyzing them. How does the stub mechanism work? Is the stub loaded first and then loading the native code, or is the stub skipped if the native code is present? I built `python-igraph` on my Linux machine, but I don't see any `_igraph.py` being generated; am I looking in the wrong place or does this mechanism work differently across Python/`pip`/`setuptools` versions?

**Comment by ntamas** [comment]
Thanks, I'll try to wrap things up nicely in a PR in the next few days then!

> How does the stub mechanism work? Is the stub loaded first and then loading the native code, or is the stub skipped if the native code is present?

The stub is basically only a few lines of Python code that loads the C extension. I don't know why it's needed -- the stub seems to be generated by `setuptools` when the extension is packaged as a Python egg, and it seems to be the default behaviour for me when I compile the Python extension from source and run `python setup.py install`. It is not present if I build a wheel instead. The stub looks like this:

```sh
$ cat .venv/lib/python3.9/site-packages/python_igraph-0.9.0-py3.9-macosx-10.15-x86_64.egg/igraph/_igraph.py
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources
    from importlib.machinery import ExtensionFileLoader
    __file__ = pkg_resources.resource_filename(__name__, '_igraph.cpython-39-darwin.so')
    __loader__ = None; del __bootstrap__, __loader__
    ExtensionFileLoader(__name__,__file__).load_module()
__bootstrap__()
```

**Comment by tristanlatr** [comment]
More details here: https://github.com/twisted/pydoctor/pull/380#issuecomment-868761407

**Comment by tristanlatr** [comment]
Maybe the sort order issue is not fixed yet.
