### ISSUE TITLE
Support for attrs

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#304]
I understood in #298 that `attrs` built classes are supported? Or I missunderstood maybe

I havent heard about `attrs` and pydoctor yet, so I'm opening this ticket.

The thing is this code

```python
import attr
@attr.s
class SomeClass(object):
    a_number = attr.ib(default=42)
    list_of_numbers = attr.ib(factory=list)

    def hard_math(self, another_number):
        return self.a_number + sum(self.list_of_numbers) * another_number
```

Generates 

<img width="542" alt="by default 2020-12-01 at 3 08 12 PM" src="https://user-images.githubusercontent.com/19967168/100791288-09371980-33e7-11eb-87a0-c757f57ba0fe.png">

I see a couple issues here:
- The class variables should be instance variables
- The constructor should be documented as well (may be we should think of a better way to display `__init__` arguments)

What part of `attrs` is actually supported ?

**Comment by adiroiban** [comment]
AFAIK the `attrs` library has not extra support in pydoctor.

Since the members are defined at class level and there is no extra docstrings, they go with the default behavior.

In the example, I don't see any docstring to document the members and also no type hinting.

Hynek did a great job with the library and the example from https://github.com/python-attrs/attrs/blob/master/README.rst is designed to explain the main attrs features...without going into details on how to document the code.

A better example is the one at https://www.attrs.org/en/stable/types.html

```python
>>> import attr
>>> import typing

>>> @attr.s(auto_attribs=True)
... class SomeClass:
...     a_number: int = 42
...     list_of_numbers: typing.List[int] = attr.Factory(list)
```

------------
 
As the same time, I think that attr is designed for simple classes that are self explanatory .
I see `attrs` as a nice replacement for named tuples.

-----------

I have checked the https://www.attrs.org/ website and I have not seen any example with docstrings.

----------

Regarding class member vs instance member, I think that we can add hardcoded support in `pydoctor` and when it sees `attrs.ib` it will add it to instance members, even if they are defined as class members.

Might be ok if `pydoctor` could inject the default value in the documentation.

I don't know what to say about `__init__` documentation. I feel that in the context of `attrs` documenting init is just boilerplate.
Instead, pydoctor could add some note that this is an `attrs` based class and then you will know that you will init it with any public attribute.

see code from here

```python
>>> import attr, inspect
>>> @attr.s
... class C(object):
...     x = attr.ib()
>>> print(inspect.getsource(C.__init__))
def __init__(self, x):
    self.x = x
```

**Comment by mthuurne** [comment]
There is some support for `attrs`: the `type` or `default` argument is used to determine the type of an attribute (implemented in `_annotation_from_attrib()` in `astbuilder.py`). This is why `a_number` is documented as having type `int`: pydoctor sees the `default` argument receiving an integer value.

Mixing `attrs` with docstrings works fine, we even have this inside pydoctor itself:
```py
@attr.s(auto_attribs=True)
class _Unit:
    """
    A unit of time for maximum age parsing.

    @see: L{parseMaxAge}
    """

    name: str
    """The name of the unit."""

    minimum: int
    """The minimum value, inclusive."""

    maximum: int
    """The maximum value, exclusive."""
```

I agree that an attribute should be documented as an instance variable instead of a class variable.

It's not clear yet to me what the best way is to handle constructors. I'll open a separate issue for that, since it goes beyond `attrs`.

**Comment by mthuurne** [comment]
Constructors issue: #305.

**Comment by tristanlatr** [comment]
I'll close this ticket now since I got the answers I wanted. Thanks @mwhudson to have provided the right fix!
