### ISSUE TITLE
"\n" in default code directive "::" is interpreted and causes a new line in output

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#346]
Using RST docformat. 
Exemple, this docstring: 

```
c) Extend both, calling the parent functions under the same
    conditions::

      def visit_example(self, node):
          if foo:
              self.body.append('<div class="foo">\n')
          else: # call the parent method
              _html_base.HTMLTranslator.visit_example(self, node)
  
      def depart_example(self, node):
          if foo:
              self.body.append('</div>\n')
          else: # call the parent method
              _html_base.HTMLTranslator.depart_example(self, node)
```

Generates: 

![Capture d’écran, le 2021-01-15 à 13 31 27](https://user-images.githubusercontent.com/19967168/104764925-0e052200-5736-11eb-8150-9764392094da.png)

**Comment by mthuurne** [comment]
Although unexpected, I think this behavior is actually correct. Since a docstring is a Python string, a `\n` inside the string will be parsed as a newline character by the Python parser, before the docformat parser even sees the string. If this is not wanted, a raw string can be used instead:

```py
r"""
Code::

    x = 'a\nb'
"""
```

It would be worth documenting this though, because it is not intuitive.
