### ISSUE TITLE
Delete warning: Parameter name "*args" should not include asterixes

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#367]
Hi, 

The warning is triggered in : `FieldHandler._handle_param_name`. I think it should should be deleted. 

The [google docstring](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) type allow "`*args`" to be specified as such, same goes for "`**kwargs`". 

Also, `keyword` is not barely used by the community, I know we support it and it's the "right" way to declare keyword arguments but the vast majority of the case the docstring of "`**kwargs`" will only redirect to another function that actually document the arguments. Like 

```
:param url: the request URL
:param \*\*kwargs: see `requests.request`
```

and `my_func` would contains the actual description of the arguments. And that should be a valid thing to do. 

So this warning makes no sens to me. 

Also "`*args`" and "`**kwargs`" should be listed last.

**Comment by mthuurne** [comment]
> The warning is triggered in : `FieldHandler._handle_param_name`. I think it should should be deleted.

In general, I prefer tools to complain when auto-correcting parts of the input, rather than doing it silently. This helps keep the input consistent, which makes searching the documented code more reliable.

> The [google docstring](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) type allow "`*args`" to be specified as such, same goes for "`**kwargs`".

According to the linked docs, the asterixes are not just allowed, but mandatory. I'd prefer the google format parser to check for the asterixes, warn if they are **not** present, then strip them off when converting to RST.

If that is too complex to implement, we could settle for stripping off all leading asterixes without checking the kind of parameter.

> Also, `keyword` is not barely used by the community, I know we support it and it's the "right" way to declare keyword arguments but the vast majority of the case the docstring of "`**kwargs`" will only redirect to another function that actually document the arguments. Like
> 
> ```
> :param url: the request URL
> :param **kwargs: see `requests.request`
> ```
> 
> and `my_func` would contains the actual description of the arguments. And that should be a valid thing to do.

The `keyword` field is an option to document individual keywords, but as far as I know you can just document the collection instead, provided you use only the name itself without any asterixes.

> Also "`*args`" and "`**kwargs`" should be listed last.

Parameters are listed in source code order, as far as I know. That means that keyword-only arguments come after `*args`. Are you saying that you want `*args` last even if there are keyword-only arguments? Or that `*args` and `**kwargs` aren't actually listed in source code order?

**Comment by tristanlatr** [comment]
>  I'd prefer the google format parser to check for the asterixes, warn if they are not present, then strip them off when converting to RST.

I think the  "*args" and "**kwargs" should be rendered with the asterixes in the HTML, that makes more sens because it's more close to what we have in the source. So we would also accept them inside the `:param:` field, that's what I'm saying. 

But the other option is to strip the asterixes inside `pydoctor.napoleon` and that solves the issue too (but the pages would be rendered without the asterixes)

For the order, sticking to source is best, your right.

**Comment by tristanlatr** [comment]
To be clear, the following is proposed: 
- Render the asterixes of "*args" and "**kwargs" in the HTML pages as is. 
- Show inexistent documented parameters before "**kwargs", otherwise stick to the source order
