### ISSUE TITLE
Contents of C extension modules are missing from the name index

### ISSUE THREAD

**Issue by ntamas** [twisted/pydoctor#388]
It seems like classes or methods defined in C extension modules are missing from the indexes. An example is the API documentation of `python-igraph`. For instance, the `igraph._igraph` module contains a class named `GraphBase` ([link](https://igraph.org/python/doc/api/igraph._igraph.GraphBase.html)), but neither `GraphBase` itself nor any method of `GraphBase` appears in the [name index](https://igraph.org/python/doc/api/nameIndex.html), although it is visible in the [class index](https://igraph.org/python/doc/api/classIndex.html).

**Comment by tristanlatr** [comment]
Hi @ntamas ,

I think that the object are actually there but they are hidden because they are private (with the `private` CSS class). Here, the GraphBase class it's part of a private module, this is why it's considered private.

The default behaviour is to have a JS button that can toggle from private/public view, but it looks like you override this in your API docs generation such that the toggle button is not present/not visible.

In order to have everything considered as public we need to fix #36. 

OR you can use the following System class and pass it's name with `--system-class`

```python
import pydoctor

class EverythingPublicSystem(pydoctor.zopeinterface.ZopeInterfaceSystem):
    def privacyClass(self, documentable):
        """
        All objects are always VISIBLE. 
        """
        return pydoctor.model.PrivacyClass.VISIBLE
```

OR you can use the new `--template-dir` option and override some CSS rules with the `extra.css` template file like

```css
body.private-hidden .private {
    display: inherit!important;
}
```

see [docs](https://pydoctor.readthedocs.io/en/latest/customize.html#include-custom-html)

**Comment by tristanlatr** [comment]
Or Maybe I'm mistaken because it's weird that it shows up in the Class index...

**Comment by ntamas** [comment]
Indeed they are only hidden but they are still there!

The weirdness is then in the class index where `igraph._igraph.GraphBase` is classified as not private, but `igraph._igraph.Edge` is private. The only difference between them is that `igraph.Graph` (a public class) inherits from `igraph._igraph.GraphBase`.

**Comment by ntamas** [comment]
Anyhow, since this is not a real bug then but a problem with our CSS, I'm gonna close the issue. Sorry for the noise.

**Comment by tristanlatr** [comment]
> The only difference between them is that igraph.Graph (a public class) inherits from igraph._igraph.GraphBase.

That's actually an expected behaviour. Not sure if it should be changed. 

https://github.com/twisted/pydoctor/blob/3514a00369010df432a08af0535594ca7c2d80ec/pydoctor/templatewriter/summary.py#L104
