### ISSUE TITLE
Pydoctor is slow if there are many subclasses (caching for summary stan)

### ISSUE THREAD

**Issue by not-my-profile** [twisted/pydoctor#497]
```
$ wget -O nodes.py https://sourceforge.net/p/docutils/code/HEAD/tree/tags/docutils-0.17.1/docutils/nodes.py?format=raw
$ time pydoctor nodes.py
...
pydoctor nodes.py  14.44s user 0.27s system 99% cpu 14.744 total
```

`nodes.py` contains 133 classes, generating documentation for it with pydoctor takes over 14 seconds on my machine.

It seems like Pydoctor is doing a bunch of work (parsing reST, resolving links in reST) for each subclass, e.g:

```python
class paragraph(General, TextElement): pass
class compound(General, Element): pass
class container(General, Element): pass
class bullet_list(Sequential, Element): pass
class enumerated_list(Sequential, Element): pass
class list_item(Part, Element): pass
class definition_list(Sequential, Element): pass
class definition_list_item(Part, Element): pass
class term(Part, TextElement): pass
class classifier(Part, TextElement): pass
class definition(Part, Element): pass
class field_list(Sequential, Element): pass
class field(Part, Element): pass
class field_name(Part, TextElement): pass
class field_body(Part, Element): pass
```

I think it would make sense to introduce some caching to avoid doing the same work multiple times.

**Comment by tristanlatr** [comment]
I get your point. I think the solution would be to cache the results of the EpydocLinker. In order to do that, we need to store and associate one EpydocLinkers to one context object (maybe simply getLinker() method on all Documentables), implement caching on the linker and reuse the same linker every time we need to link within that context. One exception would be the summary generation, they would use a different Linker instance because of #478

**Comment by tristanlatr** [comment]
I haven’t run benchmark to see if the linker is actually a bottleneck, but it definitely could be, because we’re doing a lot of funcky stuff to resolve links.

**Comment by tristanlatr** [comment]
I think what's slow if the calls to `flatten` function.  And re-generating the summaries of each object all the time. I have some =thing reasy to fix this issue as well as fixes #478 by improving the linker by providing caching. 

After that, the summaries should also be cached IMO.

**Comment by tristanlatr** [comment]
See discussion about docstring linker caching here: https://github.com/twisted/pydoctor/pull/498#issuecomment-1050516761

The proper way of resolving this issue is to have both https://github.com/twisted/pydoctor/issues/86 and https://github.com/twisted/pydoctor/issues/421 fixed, compute the summary document from a version with already resolved links in it and im.plement caching for docstring and summary stan

**Comment by tristanlatr** [comment]
I've implemented caching for summaries, it made pydoctor about two times more fast for generating the `nodes.py` docs.

From about 38 seconds to 21 seconds with the new attribute `Documentable.parsed_summary:ParsedDocstring`
