### ISSUE TITLE
Vendor lunr.py inside pydoctor

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#523]
Since pydoctor is published as a debian package, all it's dependencies should also be available in the debians repo.

I've asked the maintainer of `lunr.py` if they wanted to published to package, and they [answered](https://github.com/yeraydiazdiaz/lunr.py/issues/113) no.

So I think we should vendor lunr.py inside pydoctor. 

I think I'll go with simply adding the package lurn to the top level directory. I'll add a note on the contributing section. 
Any other advise on how to do that @adiroiban ?

**Comment by adiroiban** [comment]
I have never vendored a python package :)

I would say that the vendoring should not be done inside pydoctor setup.py / main source code, but instead vendor inside the Debian package source code - https://salsa.debian.org/python-team/packages/pydoctor/-/tree/debian/master/debian 

I see that  Carsten Schoenert is the Debian maintainer , but I don't know if there is there is an associated GitHub Account.

I am expecting that 99% of the pydoctor users are getting it via pypi, so it would make more sense to vendor only for non pypi users.


-----------

One option to manually file copy is to use git submodules https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by tristanlatr** [comment]
Maybe @tijuca would know ?

Thanks!

**Comment by tijuca** [comment]
Hi,

for completeness, I'm not **the** maintainer of the pydoctor in Debian, I was one of the persons who has done the latest uploads into the archive. pydoctor is so called Team maintained, means there is not exactely one maintainer responsible to keep the package up to date, it's more a group of people who are willing to do the work.

Now to the possible vendoring of third party stuff and available package dependencies in Debian.
Debian dislike to use vendored stuff and encourages package maintainers to not use vendored third party package were ever this is doable. The reasoning behind this is simply because from a security perspective such included stuff is almost a nightmare and simply updating a complete package within a release cycle is by the Debian Free Software Guidlines (DFSG) not possible. This ends in lots of extra time the package maintainers and the security team need to do to fix potential security issues or also broken functionality for every single package that is using vendored stuff. Of course it's less effort to just correct the one package that ten other packages are using.

On the other side not every depending package is available in the archive or is not maintained actively so other packages might to use the vendored extras within a package. So for a real example the Lunar.js library isn't packaged yet in den Debian nor has someone written yet the intention (a so called [ITP](https://www.debian.org/devel/wnpp/prospective)) to do this. That's one of the reasons why pydoctor isn't yet updated in Debian to the latest upstream release. I'm not familiar enough with packaging of JS related packages in Debian.
There are some upstream packages that need recent third party software which can't provided in Debian due the DFSG after a release of a stable version. The are some exceptions made to provide these package within Debian stable, Firefox and Thunderbird comes here to my mind, but there are just a few packages that have such an exception.

My advice (and wish) for pydoctor would be to not doing vendoring of third party software or modules but rather explain (in the README e.g.) why 3rd party library `extra` is required and by which version so the maintainers within the Linux distributions can decide what to do. And a bonus would be if pydoctor could be still simply be used as usual without some lunar.js library would be around.

"Solving and entangling" vendored packages within a main package costs always time and energy. Such time I (and other Debian Developers too) rather would invest into updating (or packaging) depending packages.

**Comment by adiroiban** [comment]
+1 for having lunr.py as a debian package.

@tristanlatr who really needs pydoctor in Debian ?
Maybe that person can help and create a package for lunr.py

I don't think that is fair to ask the lunr.py developer to provide package helpers for every possible distribution.

At the same time, I am expecting that pydoctor is only use for developer purposes, so there is always a virtualenv available that can be use to get pydoctor.

**Comment by tijuca** [comment]
I was wrong about lunar.js isn't packaged, it is. :smile: 

https://tracker.debian.org/pkg/node-lunr

And I see now you are talking about lunr.**py**, not lunr.js, my fault. I can take care of introducing lunr.py into Debian. Will take a bit of time. So I'd say no need to vendor this lib into pydoctor.

**Comment by tijuca** [comment]
Thanks to the really quick processing of the source package [python-lunr](https://tracker.debian.org/pkg/python-lunr) by the FTPmasters in Debian the new package dependency on lunr.py is available in Debian starting in the suite `unstable`. If time permits I'll work on updating pydoctor next.

**Comment by tristanlatr** [comment]
Thanks @tijuca!

I’ll close this ticket now.

**Comment by tristanlatr** [comment]
@tijuca heads up for the git-buildpackage repository: Pydoctor switch to configargparse to handle argument and configuration file parsing ([more infos](https://pydoctor.readthedocs.io/en/latest/help.html)). This includes breaking changes for the configuration file format.

**Comment by tijuca** [comment]
Thanks for the feedback @tristanlatr

It's probably time to involve @agx too into news about the latest changes in pydoctor. he knows best about `git-buildpackage` as the creator of this package and might have additional information about the needs for the documentation in `git-buildpackage`. The correct place for further discussion would be #525 I guess. Or if working on the original Debian issue is preferred than information exchange should happen through [#1005468](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005468).

**Comment by agx** [comment]
@tristanlatr most of the options seems to translate 1:1 (`htmloutput` -> `html-output`), I didn't see a replacement for `packages: gbp,tests/doctests/` though.

**Comment by tristanlatr** [comment]
Sorry but positional arguments can’t be passed with a confit file… you could use “add-package” from the confit file, but it’s a deprecated arguments.

**Comment by tristanlatr** [comment]
Hi @agx, I'm not against considering removing the deprecation to one of the arguments `--add-package` or `--add-module.` to make it clearly possible to configured source paths with config file. Note that it's already possible actually, but not documented. 

You can write something like: 

```
html-output = build/api
add-package =
    gbp
    tests/doctests/
```

Please open an issue asking to remove the deprecation of this argument if you thing it's worth supporting it officially.

Tell me what you think,
