### ISSUE TITLE
Recognize TypeVarTuple as a type variable

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#629]
TypeVarTuple has been introduced in python 3.11 and is also accessible through the typing_extensions module. I don’t think we need yet another kind for variadic generics, we can use the TYPE_VARIABLE kind we already introduced in #578.

More infos: https://peps.python.org/pep-0646/

**Comment by glyph** [comment]
> @glyph, can you clarify what you meant by « I kind of hope Pydoctor eventually grows support for Annotated » ? What feature you are hoping for exactly ?

```
def foo(bar: int, baz: int) -> str:
    """
    do foo

    @param bar: the bar parameter
    @param baz: the baz parameter
    @return: some text
    """
```

would become something like

```
from pydoctor.runtime import Documented as Doc
def foo(bar: Doc[int, "the bar parameter"], baz: Doc[int, "the baz parameter"]) -> Doc[str, "some text"]:
    "do foo"
```

which would use `Annotated` under the hood.   Maybe that exact spelling isn't possible and it'd need to be like `Annotated[int, Doc("")]` or something wordier, but something along those lines, which is to say, making there be only one parameter list, rather than two, so you don' thave to repeat the names in the signature, exactly match them, and burn up a whole bunch of additional vertical space in order to do it.

**Comment by glyph** [comment]
> Oh and I suppose `typing.Annotated` aliases should show up as a type variables as well ?

I think you need a separate type. They're not the same as `TypeVar`s; the caller has to know the difference because they're used differently.

**Comment by glyph** [comment]
> `baz: Doc[int, "the baz parameter"],`

I should probably clarify: that usage of `Annotated` has nothing whatsoever to do with this feature, and should probably be discussed elsewhere :)
