### ISSUE TITLE
Search bar doesn't always yield the expected results

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#648]
When searching for "ensure parsed docstring", I was expecting to see the [pydoctor.epydoc2stan.ensure_parsed_docstring()](https://pydoctor.readthedocs.io/en/latest/api/pydoctor.epydoc2stan.html#ensure_parsed_docstring) function show up, but it doesn't:

<img width="860" alt="by default 2022-09-08 at 1 29 50 PM" src="https://user-images.githubusercontent.com/19967168/189187300-c3b9dcb3-290e-4d4a-9fe6-0b0e7e12c543.png">

Maybe we can workaround the issue by adding wildcard at the end of the search query if the result did not yield any results, but it would be an uncommon behaviour. I'm unsure of the root cause if the issue, the lunr index building / searching seem quite complicated and might be the issue here. Because I've tried to make sure the object are also indexed by their split names as well, such that thins kind of query works. But it doesn't always.

**Comment by ntamas** [comment]
We have been running into this issue over there with `python-igraph` as well - see [this issue](https://github.com/igraph/python-igraph/issues/611) and [this comment](https://github.com/igraph/python-igraph/issues/611#issuecomment-1315302069) in particular. The problem is that Lunr uses some kind of a similarity threshold, and for long keywords you need to enter quite a few characters from the keyword to get above the similarity threshold between the query and the keyword.

I am all in favour of adding the behaviour that you proposed above, or a simpler variant of it: when the search query contains no spaces and no asterisks, add an asterisk to the end and pass _that_ to Lunr. In all other cases we assume that the user knows the Lunr syntax and wants the search string to be passed down to the Lunr engine exactly. You may even make this behaviour opt-in in a configuration file in order not to break behaviour for existing sites and we will happily opt in into this.
