### ISSUE TITLE
Building docs directly from package name, by downloading sources from pypi

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#703]
I think this bit of [code](https://github.com/tristanlatr/pypi-doc) is worth being part of pydoctor itself. 

It could be very useful for developers to be able to build docs of any packages on pypi in seconds. An potentially build a dash docset after. 

#536 should probably be taken care of before we propose this kind of feature.

Tell me what you think @glyph @adiroiban

**Comment by adiroiban** [comment]
I don't know. I don't find it useful.... but this does not mean it is not.

I think that API doc is important, but 90% I am readying the apidocs from the source code.

I am in alert mode when it comes to pypi... so downloading and executing random code from PyPi is like looking for trouble for me.

as you mention, unsecure directives should be disabled first ... but if a project has custom directives.. I don't know what you can do.

**Comment by glyph** [comment]
> @adiroiban, we're 100% not executing any kind of code, unless option `--introspect-c-modules` is provided.

While this is true, the `ast` module is not *particularly* hardened because it's so often adjacent to executing code. That's not to say that security bugs won't be fixed, but I would want to be cautious about being too expansive (at least until it's got any other kind of sandboxing, it should be considered only slightly less risky than `pip install` of a package)
