### ISSUE TITLE
Allow anchors in apilinks

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#74]
Right now, apilinks extension for sphinx does not allow adding a anchor/hash in the URL.

anchors are useful for linking to a specific method.

This ticket was initially raised here https://twistedmatrix.com/trac/ticket/6954

---

Imported from Launchpad using lp2gh.
- date created: 2014-02-20T09:03:25Z
- owner: adiroiban
- the launchpad url was https://bugs.launchpad.net/bugs/1282458

**Comment by mthuurne** [comment]
I think that with the intersphinx support, pydoctor already has a solution for this. What needs to happen is for Twisted's docs to use proper intersphinx links instead of the `apilinks` extension.

Twisted ticket: [10057](https://twistedmatrix.com/trac/ticket/10057)
Once Twisted uses intersphinx, we can drop support for function pages, see #289.
